version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  nestjs:
    build: .
    container_name: nestjs
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    # command: sh -c "npm run build && npx typeorm migration:run -d ./dist/data-source.js && npm run start:dev"

volumes:
  mysql-data:
